import { Testimonial, StatItem } from "./types";

// ==========================================
// LANDING PAGE CONSTANTS
// ==========================================

export const FEATURES_DATA = [
  {
    iconName: "brain" as const,
    title: "AI-Powered Learning",
    description:
      "Personalized courses generated by advanced AI algorithms tailored to your learning style and pace.",
  },
  {
    iconName: "book" as const,
    title: "Interactive Lessons",
    description:
      "Engage with hands-on coding exercises, quizzes, and real-time feedback to master new skills.",
  },
  {
    iconName: "message" as const,
    title: "AI Tutor Chat",
    description:
      "Get instant help and explanations from our AI tutor available 24/7 to answer your questions.",
  },
  {
    iconName: "trophy" as const,
    title: "Progress Tracking",
    description:
      "Monitor your learning journey with detailed analytics, achievements, and personalized insights.",
  },
  {
    iconName: "code" as const,
    title: "Code Assessments",
    description:
      "Test your skills with automated coding challenges and get instant feedback on your solutions.",
  },
  {
    iconName: "users" as const,
    title: "Self Learning",
    description: "Join a self learning experience.",
  },
];

export const STATS: StatItem[] = [
  { number: "10K+", label: "Active Learners" },
  { number: "500+", label: "Courses Available" },
  { number: "95%", label: "Success Rate" },
  { number: "24/7", label: "AI Support" },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    name: "Exmp",
    role: "Software Engineer",
    content:
      "The AI tutor helped me learn React in just 2 weeks. The personalized approach made all the difference!",
    rating: 5,
  },
  {
    name: "Exmp",
    role: "Data Scientist",
    content:
      "Best learning platform I've used. The coding assessments are challenging but fair, and the feedback is incredibly helpful.",
    rating: 5,
  },
  {
    name: "Exmp",
    role: "Frontend Developer",
    content:
      "The community aspect is amazing. I've made great connections and learned so much from other learners.",
    rating: 5,
  },
];

// ==========================================
// DIFFICULTY LEVELS
// ==========================================

export const DIFFICULTY_LEVELS = [
  { value: "all", label: "All Levels" },
  { value: "beginner", label: "Beginner" },
  { value: "intermediate", label: "Intermediate" },
  { value: "advanced", label: "Advanced" },
] as const;

// ==========================================
// TAG COLORS
// ==========================================

export const TAG_COLORS = [
  "bg-gray-100 text-gray-800",
  "bg-gray-200 text-gray-900",
  "bg-black text-white",
  "bg-gray-300 text-gray-900",
  "bg-gray-100 text-black",
  "bg-gray-200 text-gray-800",
] as const;

// ==========================================
// APP CONFIG
// ==========================================

export const APP_CONFIG = {
  name: "AI Learning Assistant",
  description: "Master programming skills with personalized AI courses",
  tagline: "Learn to Code with AI-Powered Education",
  copyright: `© ${new Date().getFullYear()} AI Learning Assistant. All rights reserved.`,
  githubUrl: "https://github.com/Annieeeee11/AI-Learning-Assistant",
} as const;

// ==========================================
// ROUTES
// ==========================================

export const ROUTES = {
  home: "/",
  auth: "/auth",
  dashboard: "/dashboard",
  courses: "/courses",
  course: (id: string) => `/course/${id}`,
  lesson: (id: string) => `/lesson/${id}`,
  assessment: (id: string) => `/assessment/${id}`,
  assessments: "/assessments",
  generateCourse: "/generate-course",
  chat: "/chat",
} as const;

// ==========================================
// DEFAULT VALUES
// ==========================================

export const DEFAULTS = {
  courseDuration: "4 weeks",
  estimatedHours: 0,
  progressPercentage: 0,
} as const;

