"use client";

import { Button } from "@/components/ui/button";
import { ModeToggle } from "@/components/modeToggle";
import { 
  IconBrain, 
  IconBook, 
  IconTrophy, 
  IconMessageCircle, 
  IconArrowRight,
  IconUsers,
  IconStar,
  IconCode,
  IconRocket
} from "@tabler/icons-react";
import Link from "next/link";

export default function LandingPage() {
  const features = [
    {
      icon: <IconBrain className="w-6 h-6" />,
      title: "AI-Powered Learning",
      description: "Personalized courses generated by advanced AI algorithms tailored to your learning style and pace."
    },
    {
      icon: <IconBook className="w-6 h-6" />,
      title: "Interactive Lessons",
      description: "Engage with hands-on coding exercises, quizzes, and real-time feedback to master new skills."
    },
    {
      icon: <IconMessageCircle className="w-6 h-6" />,
      title: "AI Tutor Chat",
      description: "Get instant help and explanations from our AI tutor available 24/7 to answer your questions."
    },
    {
      icon: <IconTrophy className="w-6 h-6" />,
      title: "Progress Tracking",
      description: "Monitor your learning journey with detailed analytics, achievements, and personalized insights."
    },
    {
      icon: <IconCode className="w-6 h-6" />,
      title: "Code Assessments",
      description: "Test your skills with automated coding challenges and get instant feedback on your solutions."
    },
    {
      icon: <IconUsers className="w-6 h-6" />,
      title: "Self Learning",
      description: "Join a self learning experience."
    }
  ];

  const stats = [
    { number: "10K+", label: "Active Learners" },
    { number: "500+", label: "Courses Available" },
    { number: "95%", label: "Success Rate" },
    { number: "24/7", label: "AI Support" }
  ];

  const testimonials = [
    {
      name: "Exmp",
      role: "Software Engineer",
      content: "The AI tutor helped me learn React in just 2 weeks. The personalized approach made all the difference!",
      rating: 5
    },
    {
      name: "Exmp",
      role: "Data Scientist",
      content: "Best learning platform I've used. The coding assessments are challenging but fair, and the feedback is incredibly helpful.",
      rating: 5
    },
    {
      name: "Exmp",
      role: "Frontend Developer",
      content: "The community aspect is amazing. I've made great connections and learned so much from other learners.",
      rating: 5
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="flex justify-between items-center p-6 border-b">
        <div className="flex items-center gap-2">
          <IconBrain className="w-8 h-8 text-primary" />
          <h1 className="text-2xl font-bold text-foreground">AI Learning Assistant</h1>
        </div>
        <div className="flex items-center gap-4">
          <ModeToggle />
          <Link href="/auth">
            <Button variant="outline">Sign In</Button>
          </Link>
          <Link href="/auth">
            <Button>Get Started</Button>
          </Link>
        </div>
      </header>

      <section className="py-20 px-6 text-center">
        <div className="max-w-4xl mx-auto">
          <div className="flex justify-center mb-6">
            <div className="w-20 h-20 bg-primary rounded-full flex items-center justify-center">
              <IconRocket className="w-10 h-10 text-primary-foreground" />
            </div>
          </div>
          <h1 className="text-5xl font-bold text-foreground mb-6">
            Learn to Code with
            <span className="text-primary"> AI-Powered</span> Education
          </h1>
          <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
            Master programming skills with personalized AI courses, interactive coding challenges, 
            and 24/7 AI tutor support. Start your coding journey today!
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/auth">
              <Button size="lg" className="w-full sm:w-auto">
                Start Learning Free
                <IconArrowRight className="w-4 h-4 ml-2" />
              </Button>
            </Link>
            {/* <Button variant="outline" size="lg" className="w-full sm:w-auto">
              Watch Demo
            </Button> */}
          </div>
        </div>
      </section>

      <section className="py-16 px-6 bg-muted/50">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="text-3xl font-bold text-primary mb-2">{stat.number}</div>
                <div className="text-muted-foreground">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-foreground mb-4">
              Why Choose AI Learning Assistant?
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Our platform combines cutting-edge AI technology with proven learning methodologies 
              to deliver an unparalleled educational experience.
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="p-6 bg-card rounded-lg border hover:shadow-lg transition-shadow">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center text-primary mb-4">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                <p className="text-muted-foreground">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 px-6 bg-muted/50">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-foreground mb-4">
              What Our Learners Say
            </h2>
            <p className="text-muted-foreground">
              Join thousands of successful learners who have transformed their careers with our platform.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="p-6 bg-card rounded-lg border">
                <div className="flex mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <IconStar key={i} className="w-5 h-5 text-yellow-400 fill-current" />
                  ))}
                </div>
                <p className="text-muted-foreground mb-4">&quot;{testimonial.content}&quot;</p>
                <div>
                  <div className="font-semibold">{testimonial.name}</div>
                  <div className="text-sm text-muted-foreground">{testimonial.role}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl font-bold text-foreground mb-4">
            Ready to Start Your Learning Journey?
          </h2>
          <p className="text-muted-foreground mb-8 max-w-2xl mx-auto">
            Join our community of learners and start building your coding skills with AI-powered education.
            It&apos;s free to get started!
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/auth">
              <Button size="lg" className="w-full sm:w-auto">
                Create Free Account
                <IconArrowRight className="w-4 h-4 ml-2" />
              </Button>
            </Link>
            <Button variant="outline" size="lg" className="w-full sm:w-auto">
              Learn More
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-6 border-t bg-muted/50">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center gap-2 mb-4 md:mb-0">
              <IconBrain className="w-6 h-6 text-primary" />
              <span className="font-semibold">AI Learning Assistant</span>
            </div>
            <div className="text-sm text-muted-foreground">
              © 2024 AI Learning Assistant. All rights reserved.
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}